name: CI/CD Pipeline
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Installer les dépendances
        run: pip install -r requirements.txt

      - name: Exécuter les tests
        run: python -m unittest test_app.py app.y app2.py 

      - name: Analyse SonarCloud
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=wailambs
            -Dsonar.projectKey=WailAmbs_tp-ci-cd
            -Dsonar.sources=.
            -Dsonar.python.version=3
            -Dsonar.qualitygate.wait=true

      - name: Analyse de sécurité Snyk
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Déclencher le déploiement sur Render
        run: |
          curl -X POST "https://api.render.com/deploy/srv-cvht27pc1ekc738fcrk0?key=qN2D90HUbqs"
